# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 500000 # 500000 for 6h_vs_8z

runner: "parallel"
batch_size_run: 8 
buffer_size: 500
batch_size: 128
optimizer: 'adam'

t_max: 1005000

# update the target network every {} episodes
target_update_interval: 2000

# use the Q_Learner to train
mac: "n_mac"
agent: "att_rnn" # self-attention for communication
agent_output_type: q
att_heads: 8
att_embed_dim: 256

learner: "nq_learner"
mixer: "qmix"
mixing_embed_dim: 256
hypernet_embed: 256
lr: 0.001 # Learning rate for agents
td_lambda: 0.3
optimizer: 'adam'

grad_norm_clip: 20.0
use_cuda: False

name: "qmix_att_env=8_adam_td_lambda"