env: rock_sampling

env_args:
    map_name: "rock_sampling"
    env_args:
        horizon: 100
learner_log_interval: 2000
log_interval: 2000
runner_log_interval: 2000
t_max: 100500
test_interval: 20000
test_nepisode: 24
test_greedy: True