env: team_box_pushing

env_args:
    map_name: "team_box_pushing"
    env_args:
        horizon: 30
learner_log_interval: 2000
log_interval: 2000
runner_log_interval: 2000
t_max: 100500
test_interval: 2000
test_nepisode: 24
test_greedy: True